### ISSUE TITLE
Where do I get the modified MMU2S firmware?

### ISSUE THREAD

**Issue by ALittleSlow** [Ruhkukah/Prusa-Firmware#1]
Thanks for doing this! I am confused, though. In your Prusa-Firmware/Prusa MK3S Stock - compiled binary / I can see the .hex files for the MK3S, but but i don't see a corresponding TZB-MMU2S-3.0.4-BN364.hex variant for the MMU2S. Do I just use that one from the ZeroBeast? Or am I overlooking something?

**Comment by Ruhkukah** [comment]
Hi @ALittleSlow, you are right, you need to use the latest firmware from the ZeroBeast, since it doesn't need any update. I flashed the firmware **TZB-MMU2S-3.0.4-BN364.hex** found here https://github.com/TheZeroBeast/TZB-MMU2S-Firmware/releases

**Comment by ALittleSlow** [comment]
Perfect, thanks!
